version: "3"

services:
    mysql:
        container_name: mysql
        build: ./db
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 20s
            retries: 10

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        container_name: backend
        depends_on:
            mysql:
                condition: service_healthy

    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        depends_on:
            - backend
        container_name: frontend
