version: "3"

services:
    backend:
        build: ./backend
        ports:
            - "3000:3000"
        depends_on:
            - mysql
        container_name: backend

    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root

    frontend:
        build: ./frontend
        ports:
            - "8000:8000"
        depends_on:
            - backend
        container_name: frontend
