version: "2"

services:
    backend:
        build: ./backend
        ports:
            - "8080:8080"
        depends_on:
            - db
        container_name: backend

    mysql:
        container_name: mysql
        image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root

#    frontend:
#        build: ./frontend
#        ports:
#            - "80:80"
#        container_name: frontend
